INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('1', 'Ninguna');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('2', 'Obesidad');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('3', 'Diabetes');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('4', 'Traumatismo');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('5', 'Cirugía');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('6', 'HIV/SIDA');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('7', 'Cáncer');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('8', 'inmunosupresión/Neutropenia');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('9', 'Uso Esteroides');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('10', 'Embarazo');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('11', 'Neoplasias');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('12', 'Inanición');
INSERT INTO antecedentes_personales(id_ant_per, nom_ant) VALUES ('13', 'Otros');
