INSERT INTO municipios	(id_est,des_mun)		VALUES(	1	,'	Libertador Caracas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	25	,'	Alto Orinoco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	25	,'	Atabapo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	25	,'	Atures		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	25	,'	Autana		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	25	,'	Manapiare		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	25	,'	Maroa		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	25	,'	Río Negro		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Anaco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Aragua		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Bruzual		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Cajigal		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Carvajal		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Diego Bautista Urbaneja		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Freites		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Guanipa		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Guanta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Independencia		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Libertad		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	McGregor		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Miranda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Monagas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Peñalver		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Píritu		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	San Juan de Capistrano		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Santa Ana		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Simón Rodriguez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	2	,'	Sotillo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	3	,'	Achaguas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	3	,'	Biruaca		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	3	,'	Muñoz		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	3	,'	Páez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	3	,'	Pedro Camejo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	3	,'	Rómulo Gallegos		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	3	,'	San Fernando		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Camatagua		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Francisco Linares Alcántara		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Girardot		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	José Angel Lamas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	José Félix Ribas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	José Rafael Revenga		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Libertador		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Mario Briceño Iragorry		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Ocumare de la Costa de Oro		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	San Casimiro		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	San Sebastián		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Santiago Mariño		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Santos Michelena		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Tovar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Urdaneta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	4	,'	Zamora		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Alberto Arvelo Torrealba		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Andrés Eloy Blanco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Antonio José de Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Arismendi		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Barinas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Cruz Paredes		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Ezequiel Zamora		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Obispos		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Pedraza		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Rojas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	5	,'	Sosa		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Caroní		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Cedeño		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	El Callao		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Gran Sabana		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Heres		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Piar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Raúl Leoni		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Roscio		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Sifontes		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	6	,'	Padre Pedro Chien		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Bejuma		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Carlos Arvelo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Diego Ibarra		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Guacara		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Juan José Mora		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Libertador		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Los Guayos		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Miranda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Montalbán		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Naguanagua		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Puerto Cabello		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	San Diego		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	San Joaquín		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	7	,'	Valencia		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	Anzoátegui		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	Falcón		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	Girardot		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	Lima Blanco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	Pao de San Juan Bautista		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	Ricaurte		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	Rómulo Gallegos		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	San Carlos		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	8	,'	Tinaco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	9	,'	Antonio Díaz		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	9	,'	Casacoima		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	9	,'	Pedernales		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	9	,'	Tucupita		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Acosta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Buchivacoa		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Cacique Manaure		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Carirubana		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Colina		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Dabajuro		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Democracia		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Falcón		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Federación		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Jacura		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Los Taques		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Mauroa		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Miranda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Monseñor Iturriza		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Palmasola		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Petit		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Píritu		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	San Francisco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Silva		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Tocópero		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Unión		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Urumaco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	10	,'	Zamora		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Camaguán		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Chaguaramas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	El Socorro		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Sebastian Francisco de Miranda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	José Félix Ribas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	José Tadeo Monagas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Juan Germán Roscio		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Julián Mellado		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Las Mercedes		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Leonardo Infante		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Pedro Zaraza		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Ortiz		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	San Gerónimo de Guayabal		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	San José de Guaribe		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	11	,'	Santa María de Ipire		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Andrés Eloy Blanco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Crespo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Iribarren		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Jiménez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Morán		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Palavecino		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Simón Planas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Torres		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	12	,'	Urdaneta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Alberto Adriani		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Andrés Bello		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Antonio Pinto Salinas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Aricagua		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Arzobispo Chacón		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Campo Elías		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Caracciolo Parra Olmedo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Cardenal Quintero		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Guaraque		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Julio César Salas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Justo Briceño		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Libertador		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Miranda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Obispo Ramos de Lora		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Padre Noguera		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Pueblo Llano		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Rangel		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Rivas Dávila		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Santos Marquina		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Tovar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	13	,'	Tulio Febres Cordero		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Zea		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Acevedo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Andrés Bello		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Baruta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Brión		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Buroz		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Carrizal		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Chacao		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Cristóbal Rojas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	El Hatillo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Guaicaipuro		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Independencia		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Lander		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Los Salias		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Páez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Paz Castillo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Pedro Gual		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Plaza		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Simón Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Urdaneta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	14	,'	Zamora		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Acosta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Aguasay		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Caripe		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Cedeño		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Ezequiel Zamora		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Libertador		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Maturín		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Piar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Punceres		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Santa Bárbara		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Sotillo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	15	,'	Uracoa		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Antolín del Campo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Arismendi		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Díaz		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	García		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Gómez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Maneiro		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Marcano		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Mariño		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Península de Macanao		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Tubores		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	16	,'	Villalba		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Agua Blanca		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Araure		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Esteller		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Guanare		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Guanarito		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Monseñor José Vicente de Unda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Ospino		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Páez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Papelón		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	San Genaro de Boconoíto		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	San Rafael de Onoto		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Santa Rosalía		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	18	,'	Turén		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Andrés Eloy Blanco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Andrés Mata		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Arismendi		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Benítez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Bermúdez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Cajigal		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Cruz Salmerón Acosta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Libertador		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Mariño		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Mejía		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Montes		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Ribero		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	19	,'	Valdez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Andrés Bello		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Antonio Rómulo Costa		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Ayacucho		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Cárdenas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Córdoba		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Fernández Feo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Francisco de Miranda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	García de Hevia		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Guásimos		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Independencia		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Jáuregui		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	José María Vargas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Junín		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Libertad		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Libertador		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	17. Lobatera		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Michelena		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Panamericano		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Pedro María Ureña		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Rafael Urdaneta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Samuel Darío Maldonado		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	San Cristóbal		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Seboruco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Simón Rodríguez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Torbes		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	Uribante		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	20	,'	San Judas Tadeo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Andrés Bello		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Boconó		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Candelaria		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Carache		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Escuque		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	José Felipe Márquez Cañizalez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Juan Vicente Campos Elías		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	La Ceiba		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Miranda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Monte Carmelo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Motatán		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Pampán		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Pampanito		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Rafael Rangel		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	San Rafael de Carvajal		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Trujillo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Urdaneta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	21	,'	Valera		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	22	,'	Vargas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Arístides Bastidas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Bruzual		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Cocorote		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Independencia		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	José Antonio Páez		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	La Trinidad		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Manuel Monge		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Nirgua		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Peña		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	San Felipe		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Urachiche		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	23	,'	Veroes		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Almirante Padilla		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Baralt		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Cabimas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Catatumbo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Colón		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Francisco Javier Pulgar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Guajira		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Jesús Enrique Losada		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Jesús María Semprún		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	La Cañada de Urdaneta		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Lagunillas		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Machiques de Perijá		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Mara		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Maracaibo		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Miranda		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Rosario de Perijá		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	San Francisco		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Santa Rita		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Simón Bolívar		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Sucre		 ');
INSERT INTO municipios	(id_est,des_mun)		VALUES(	24	,'	Valmore Rodríguez		 ');
