--CREATE INDEX animales_index ON animales USING btree (id_ani) TABLESPACE saib;
CREATE INDEX animales_index ON animales USING btree (id_ani) TABLESPACE saib;
CREATE INDEX antecedentes_pacientes_index ON antecedentes_pacientes USING btree (id_ant_pac, id_ant_per, id_his) TABLESPACE saib;
CREATE INDEX antecedentes_personales_index ON antecedentes_personales USING btree (id_ant_per) TABLESPACE saib;
CREATE INDEX categorias__cuerpos_micosis_index ON categorias__cuerpos_micosis USING btree (id_cat_cue_mic) TABLESPACE saib;
CREATE INDEX categorias_cuerpos_index ON categorias_cuerpos USING btree (id_cat_cue) TABLESPACE saib;
CREATE INDEX centro_salud_index ON centro_salud USING btree (id_cen_sal) TABLESPACE saib;
CREATE INDEX centro_salud_pacientes_index ON centro_salud_pacientes USING btree (id_cen_sal_pac, id_his, id_cen_sal) TABLESPACE saib;
CREATE INDEX contactos_animales_index ON contactos_animales USING btree (id_con_ani, id_his, id_ani) TABLESPACE saib;
CREATE INDEX enfermedades_micologicas_index ON enfermedades_micologicas USING btree (id_enf_mic) TABLESPACE saib;
CREATE INDEX enfermedades_pacientes_index ON enfermedades_pacientes USING btree (id_enf_pac, id_his, id_enf_mic) TABLESPACE saib;
CREATE INDEX estudios_micologicos__pacientes_index ON estudios_micologicos__pacientes USING btree (id_est_mic_pac) TABLESPACE saib;
CREATE INDEX forma_infecciones_index ON forma_infecciones USING btree (id_for_inf) TABLESPACE saib;
CREATE INDEX forma_infecciones__pacientes_index ON forma_infecciones__pacientes USING btree (id_for_pac) TABLESPACE saib;
CREATE INDEX forma_infecciones__tipos_micosis_index ON forma_infecciones__tipos_micosis USING btree (id_for_inf_tip_mic) TABLESPACE saib;
CREATE INDEX historiales_pacientes_index ON historiales_pacientes USING btree (id_his) TABLESPACE saib;
CREATE INDEX lesiones__partes_cuerpos_index ON lesiones__partes_cuerpos USING btree (id_les_par_cue) TABLESPACE saib;
CREATE INDEX lesiones_partes_cuerpos__pacientes_index ON lesiones_partes_cuerpos__pacientes USING btree (id_les_par_cue_pac) TABLESPACE saib;
CREATE INDEX localizaciones_cuerpos_index ON localizaciones_cuerpos USING btree (id_loc_cue) TABLESPACE saib;
CREATE INDEX muestras_clinicas_index ON muestras_clinicas USING btree (id_mue_cli) TABLESPACE saib;
--CREATE INDEX muestras_pacientes_index ON muestras_pacientes USING btree (id_mue_pas, id_his, id_mue_cli) TABLESPACE saib;
CREATE INDEX pacientes_index ON pacientes USING btree (id_pac) TABLESPACE saib;
CREATE INDEX partes_cuerpos_index ON partes_cuerpos USING btree (id_par_cue) TABLESPACE saib;
CREATE INDEX propiedades_estudios_micologicos_index ON propiedades_estudios_micologicos USING btree (id_pro_est_mic) TABLESPACE saib;
CREATE INDEX tipos_consultas_index ON tipos_consultas USING btree (id_tip_con) TABLESPACE saib;
CREATE INDEX tipos_consultas_pacientes_index ON tipos_consultas_pacientes USING btree (id_tip_con_pac, id_tip_con, id_his) TABLESPACE saib;
CREATE INDEX tipos_estudios_micologicos_index ON tipos_estudios_micologicos USING btree (id_tip_est_mic) TABLESPACE saib;
CREATE INDEX tipos_micosis_index ON tipos_micosis USING btree (id_tip_mic) TABLESPACE saib;
CREATE INDEX tratamientos_index ON tratamientos USING btree (id_tra) TABLESPACE saib;
CREATE INDEX tratamientos_pacientes_index ON tratamientos_pacientes USING btree (id_tra_pac, id_his, id_tra) TABLESPACE saib;