/*DROP TABLE paises CASCADE;
DROP TABLE estados CASCADE;
DROP TABLE municipios CASCADE;
DROP TABLE parroquias CASCADE;*/

ALTER TABLE pacientes
	DROP COLUMN pai_pac,
	DROP COLUMN est_pac,
	DROP COLUMN mun_pac,
	DROP COLUMN par_pac,
	ADD COLUMN id_pai INTEGER,
	ADD COLUMN id_est INTEGER,
	ADD COLUMN id_mun INTEGER,
	ADD COLUMN id_par INTEGER
	
	;

CREATE TABLE paises(
	id_pai SERIAL NOT NULL PRIMARY KEY,
	des_pai CHARACTER VARYING(100)
);
CREATE TABLE estados(
	id_est SERIAL NOT NULL PRIMARY KEY,
	des_est CHARACTER VARYING(100),
	id_pai INTEGER
	
);
CREATE TABLE municipios(
	id_mun SERIAL NOT NULL PRIMARY KEY,
	des_mun CHARACTER VARYING(100),
	id_est INTEGER
);
CREATE TABLE parroquias(
	id_par SERIAL NOT NULL PRIMARY KEY,
	des_par CHARACTER VARYING(100),
	id_mun INTEGER
);



ALTER TABLE pacientes
	ADD CONSTRAINT pacientes_id_pai_fkey FOREIGN KEY(id_pai) REFERENCES paises(id_pai) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	ADD CONSTRAINT  pacientes_id_est_fkey FOREIGN KEY(id_est) REFERENCES estados (id_est) MATCH SIMPLE
	ON UPDATE CASCADE ON DELETE CASCADE,
	ADD CONSTRAINT  pacientes_id_mun_fkey FOREIGN KEY(id_mun) REFERENCES municipios (id_mun) MATCH SIMPLE
	ON UPDATE CASCADE ON DELETE CASCADE,
	ADD CONSTRAINT  pacientes_id_par_fkey FOREIGN KEY(id_par) REFERENCES parroquias (id_par) MATCH SIMPLE
	ON UPDATE CASCADE ON DELETE CASCADE;	

ALTER TABLE estados
	ADD CONSTRAINT estados_id_pai_fkey FOREIGN KEY(id_pai) REFERENCES paises (id_pai) MATCH SIMPLE
	ON UPDATE CASCADE ON DELETE CASCADE;
	

ALTER TABLE municipios
	ADD CONSTRAINT municipios_id_est_fkey FOREIGN KEY(id_est) REFERENCES estados (id_est) MATCH SIMPLE
	ON UPDATE CASCADE ON DELETE CASCADE;
	

ALTER TABLE parroquias
	ADD CONSTRAINT parroquias_id_mun_fkey FOREIGN KEY(id_mun) REFERENCES municipios (id_mun) MATCH SIMPLE
	ON UPDATE CASCADE ON DELETE CASCADE;
	