INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('1', 'Pelo');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('2', 'Escama');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('3', 'Uñas');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('4', 'Exudado');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('5', 'Biopsia Piel');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('6', 'Biopsia Otros Órganos');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('7', 'Líquido Peritoneal');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('8', 'Líquido Sinovial');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('9', 'Líquido Cefalorraquídeo(LCR)');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('10', 'Líquido Pleural');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('11', 'Lavado Bronquial');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('12', 'Esputo Espontáneo');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('13', 'Esputo Inducido');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('14', 'Aspirado Traqueal');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('15', 'Cepillado Protegido');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('16', 'Punción Pulmonar');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('17', 'Punción Pleural');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('18', 'Médula Ósea');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('19', 'Sangre');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('20', 'Exudado Vaginal');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('21', 'Orina');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('22', 'Heces');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('23', 'Cateterismo');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('24', 'Sondaje');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('25', 'Bolsa Colectora');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('26', 'Cavidad Oral');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('27', 'Exudado Nasal');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('28', 'Muestras Ópticas');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('29', 'Exudado Conjuntival');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('30', 'Raspado Corneal');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('31', 'Aspirado Ocular');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('32', 'Lentes de Contacto');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('33', 'Catéteres Intravasculares');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('34', 'Catéteres Diálisis Peritoneal');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('35', 'Prótesis');
INSERT INTO muestras_clinicas(id_mue_cli, nom_mue_cli)VALUES ('36', 'Otros');

